datasets:
  - chain_id: mainnet
    module_name: db_out
    module_hash: 5b21ee0834a2c082a0befea1b71f771dc87d0f5e
    manifest: https://github.com/pinax-network/substreams-erc20/releases/download/v1.5.0/erc20-clickhouse-v1.5.0.spkg
    schema: a93c28ffeb29784264abec63228b5c7e
    engine: clickhouse

  - chain_id: base
    module_name: db_out
    module_hash: 5b21ee0834a2c082a0befea1b71f771dc87d0f5e
    manifest: https://github.com/pinax-network/substreams-erc20/releases/download/v1.5.0/erc20-clickhouse-v1.5.0.spkg
    schema: a93c28ffeb29784264abec63228b5c7e
    engine: clickhouse

  - chain_id: bsc
    module_name: db_out
    module_hash: 5b21ee0834a2c082a0befea1b71f771dc87d0f5e
    manifest: https://github.com/pinax-network/substreams-erc20/releases/download/v1.5.0/erc20-clickhouse-v1.5.0.spkg
    schema: a93c28ffeb29784264abec63228b5c7e
    engine: clickhouse

  - chain_id: arbitrum-one
    module_name: db_out
    module_hash: 5b21ee0834a2c082a0befea1b71f771dc87d0f5e
    manifest: https://github.com/pinax-network/substreams-erc20/releases/download/v1.5.0/erc20-clickhouse-v1.5.0.spkg
    schema: a93c28ffeb29784264abec63228b5c7e
    engine: clickhouse
